version: 2
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: gls

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
